name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-debug:
    
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up LLVM on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
          sudo apt-get install build-essential
          sudo apt-get install cmake

      - name: Configure CMake (Linux)
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DENABLE_CTEST=On
          cmake --build ${{github.workspace}}/build

      - name: Build and Test
        working-directory: ${{github.workspace}}/build
        run: |
          make -j 16
          ctest -j 16 --stop-on-failure

  build-linux-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up LLVM on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
          sudo apt-get install build-essential
          sudo apt-get install cmake

      - name: Configure and build with CMake (Linux)
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_CTEST=On

      - name: Build and Test
        working-directory: ${{github.workspace}}/build
        run: |
          make -j 16
          ctest -j 16 --stop-on-failure

      



