# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-debug:
    runs-on: ubuntu-latest

    steps:

      - name: Set up LLVM on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
          sudo apt-get install build-essential
          sudo apt-get install cmake

      - name: Configure and build with CMake (Linux)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CTEST=On ..
          make -j 'nproc'

      - name: Test
        run: |
          ctest -j 'nproc' --stop-on-failure

  build-linux-release:
    runs-on: ubuntu-latest

    steps:

      - name: Set up LLVM on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm
          sudo apt-get install build-essential
          sudo apt-get install cmake

      - name: Configure and build with CMake (Linux)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CTEST=On ..
          make -j 'nproc'

      - name: Test
        run: |
          ctest -j 'nproc' --stop-on-failure
      



